"""Adding orders table and description to product

Revision ID: 75e1952419bb
Revises: 
Create Date: 2024-11-24 17:37:53.871122

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75e1952419bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rc_cardapio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rc_cardapio',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('prod_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('prod_price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('categoria', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
